# Generated by Django 5.0.11 on 2025-03-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_super', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sys_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripBranchModel',
            fields=[
                ('branch_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fin_mf_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripDetailsModel',
            fields=[
                ('trip_ticket_id', models.BigIntegerField()),
                ('branch_id', models.BigIntegerField()),
                ('branch_name', models.CharField(max_length=255)),
                ('trip_ticket_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ref_trans_date', models.DateTimeField()),
                ('full_address', models.TextField()),
                ('trans_name', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('branch_charges', models.DecimalField(decimal_places=2, max_digits=18)),
                ('document_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'scm_tr_trip_ticket_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripDriverModel',
            fields=[
                ('entity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fin_mf_entity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripTicketModel',
            fields=[
                ('trip_ticket_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vehicle_id', models.BigIntegerField()),
                ('plate_no', models.CharField(max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('asst_entity_id', models.BigIntegerField()),
                ('trip_ticket_date', models.DateTimeField()),
                ('trip_ticket_delivery_type_id', models.BigIntegerField()),
                ('dispatched_by', models.BigIntegerField()),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'scm_tr_trip_ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutslipImagesModel',
            fields=[
                ('server_id', models.BigIntegerField(default=1)),
                ('trip_ticket_id', models.BigIntegerField()),
                ('upload_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_ticket_detail_id', models.BigIntegerField()),
                ('upload_text', models.CharField(blank=True, max_length=4000, null=True)),
                ('upload_remarks', models.CharField(blank=True, max_length=4000, null=True)),
                ('upload_files', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.BigIntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('is_fap', models.BooleanField(default=False)),
                ('is_candis', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scm_tr_outslip_to_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TripTicketBranchLogsModel',
            fields=[
                ('server_id', models.BigIntegerField()),
                ('trip_ticket_id', models.BigIntegerField()),
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_ticket_detail_id', models.BigIntegerField()),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.BigIntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('is_fap', models.BooleanField(default=False)),
                ('is_candis', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
                ('location_in', models.CharField(max_length=255, null=True)),
                ('ip_address_in', models.CharField(max_length=255, null=True)),
                ('location_out', models.CharField(max_length=255, null=True)),
                ('ip_address_out', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'scm_tr_trip_ticket_branch_logs',
                'managed': True,
            },
        ),
    ]
