"""
Django settings for DjangoBackend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'

MEDIA_URL = '/media/'  # URL prefix for media files
#MEDIA_ROOT = '//192.168.1.200/Central Sourcecodes/DEV/Fed/ASNUpload'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w7qolrc)hfzt-l80rvs-p*mzknxh^soeuy*e^=2@9n2(-1tj=q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
if DEBUG:
        STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = BASE_DIR / 'media'


#ALLOWED_HOSTS = ["localhost", "127.0.0.1", "10.0.2.2", "176.16.1.126",  "192.168.1.200", "103.240.120.34", "192.168.5.251", "192.168.70.190", "192.168.70.184", "192.168.126.56", "mis-federick"]
ALLOWED_HOSTS = ['*']
BASE_URL = "http://176.16.1.126:8000/api"

#BASE_URL = "http://winterpinegroup.com.ph:8000/api"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'rest_framework',
    'rest_framework_simplejwt',     
]
AUTH_USER_MODEL = "api.User"
SIMPLE_JWT = {
    'USER_ID_FIELD': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1)
}
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'djangojwtauth_cookie',
    'JWT_AUTH_REFRESH_COOKIE': 'djangojwtauth_cookie'
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Ensure JWT is configured correctly
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # Ensure that views require authentication
    ),
    
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8081",  # 
    "http://176.16.1.126:8081",  
    "http://127.0.0.1:8081",
    "http://103.240.120.34:8081",
    "http://10.0.2.2:8081",
    "http://192.168.1.200:8081",
    "http://192.168.5.251:8081",# Allow your frontend origin
    "http://192.168.70.184:8081",
    "http://192.168.126.56:8081",# Allow your frontend origin
    # Add this for development if needed
    "http://192.168.0.29:8000",
    "http://localhost:5173" ,
    "http://127.0.0.1:5173",

]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False
CORS_ORIGIN_WHITELIST = (
    '*'
)
ROOT_URLCONF = 'DjangoBackend.urls'
CORS_ALLOW_ALL_ORIGINS = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoBackend.wsgi.application'
FILE_UPLOAD_MAX_MEMORY_SIZE = 250 * 1024 * 1024
GEOIP_PATH = os.path.join(BASE_DIR, 'outslips')
GEOIP_DATABASE = 'GeoLite2-City.mmdb'
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
  # 'default': {
   #     'ENGINE': 'mssql',
    #    'NAME': 'asn_receiving',
     #   'USER': 'sa',
      #  'PASSWORD':'123',
       # 'HOST':'localhost',
    #},
DATABASES = {
 
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'bootstrap2_ret_052025',
        'USER': 'sa',
        'PASSWORD':'WTP9@!979#100420!9',
        'HOST':'192.168.0.33\MSSQLTESTSERVER',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes',
        },
        'BASE_URL': 'http://176.16.1.126:8000/api' 
    },
    'tsl_db': {
        'ENGINE': 'mssql',
        'NAME': 'test_bootstrap2_tsl',
        'USER': 'sa',
        'PASSWORD':'WTP9@!979#100420!9',
        'HOST':'192.168.0.33\MSSQLTESTSERVER',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'Encrypt=no;TrustServerCertificate=yes',
        },
        'BASE_URL': 'http://176.16.1.126:8000/tsl'
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#SFTP_STORAGE_HOST = '192.168.1.200'
#SFTP_STORAGE_ROOT = '//192.168.1.200/Central Sourcecodes/DEV/Fed/ASNUpload'
#SFTP_STORAGE_PARAMS = {
#    'username': 'mis',
#    'password': 'P@ssw0rd',
#    'allow_agent': 'false',
#    'look_for_keys': 'false',
#}
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

#DEFAULT_FILE_STORAGE = 'storages.backends.sftpstorage.SFTPStorage'
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
